CREATE TABLE "CHANNEL"
(
	"ID"				BIGINT			NOT NULL IDENTITY,
	"NAME"				LONGVARCHAR		NOT NULL UNIQUE,
	"URL"				LONGVARCHAR		NOT NULL
);


CREATE TABLE "VIDEO"
(
	"ID"				BIGINT			NOT NULL IDENTITY,
	"CHANNEL_FK"		BIGINT			NOT NULL,
	"YOUT_ID"			LONGVARCHAR		NOT NULL,
	"UPLOAD_DATE"		DATE			NOT NULL,
	"STATE"				INT				NOT NULL,
	"VIDEO_FILE"		LONGVARCHAR,
	"MP3_FILE"			LONGVARCHAR,
	
	CONSTRAINT "VIDEO_CHANNEL_FK"	FOREIGN KEY ("CHANNEL_FK")	REFERENCES "CHANNEL" ("ID")
);

CREATE INDEX "VIDEO_CHANNEL"	ON "VIDEO" ("CHANNEL_FK");