package org.ytrss.db;

public enum VideoState {

	NEW, DOWNLOADING_ENQUEUED, DOWNLOADING, DOWNLOADING_FAILED, TRANSCODING_ENQUEUED, TRANSCODING, TRANSCODING_FAILED, READY, DELETED, EXCLUDED, NOT_INCLUDED
}
