CREATE TABLE "SETTING"
(
	"ID"				BIGINT			NOT NULL IDENTITY,
	"NAME"				LONGVARCHAR		NOT NULL UNIQUE,
	"VALUE"				LONGVARCHAR		NOT NULL
);

CREATE INDEX "SETTING_NAME_IDX"	ON "SETTING" ("NAME");